#!/usr/bin/env python3
"""
Author : jim <jim@localhost>
Date   : 2022-04-27
Purpose: Take pictures with USB cameras
Version: v0.5
"""

import argparse
from typing import NamedTuple
import os
import time
import numpy as np
import cv2
import imutils
import usb.core
from threading import Thread

class Args(NamedTuple):
    """ Command-line arguments """
    directory: dir
    interval: int
    duration: int
    test: bool
    verbosity: bool
    video: bool
    videoFrames: int


# --------------------------------------------------
def get_args() -> Args:
    """ Get command-line arguments """

    parser = argparse.ArgumentParser(
        description='Take and store USB images',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('directory',
                        metavar='dir',
                        help='Storage directory for output photos')

    parser.add_argument('-i',
                        '--interval',
                        metavar='[int]',
                        help='Interval in seconds',
                        type=int,
                        default=5)

    parser.add_argument('-d',
                        '--duration',
                        metavar='[int]',
                        help='Duration of time in seconds to take pictures',
                        type=int,
                        default=15)

    parser.add_argument('--test',
                        action='store_true',
                        help='Runs the tool in test mode: Only takes one picture')

    parser.add_argument('-v',
                        '--verbosity',
                        action='store_true',
                        help='Runs the tools in verbose mode')

    parser.add_argument('-vm',
                        '--videoMode',
                        action='store_true',
                        help='Creates a timelapse from the captures')

    parser.add_argument('-vf',
                        '--videoFrames',
                        metavar='FPS',
                        help='Frames per second for the timelapse',
                        type=int,
                        default=60)

    args = parser.parse_args()

    return Args(args.directory, args.interval, args.duration, args.test, args.verbosity, args.videoMode, args.videoFrames)

# --------------------------------------------------
def captureLoop(directory, duration, interval,v, camera_index):
    ''' Defines the loop to take pictures '''

    images = int(duration/interval)
    pic_time = [x * interval for x in list(range(images))]
    count = 0
    img_num = 0
    if v:
        print(f"Taking {images} pictures")

    cap = cv2.VideoCapture(0)
    while True:
        ret, frame = cap.read()

        if count == pic_time[img_num]:
            grabbed, still = cap.read()
            if v:
                print(f"Capturing {img_num} image")
            file_path = directory + "/capture_" + str(img_num) + ".png"
            cv2.imwrite(file_path, still)

            if img_num == (images - 1):
                cap.release()
                cv2.destroyAllWindows()
                return

            img_num += 1

        # Wait 1 second and check conditions again
        time.sleep(1)
        count += 1


# --------------------------------------------------
def img2video(directory, camera, fps):

    os.chdir(directory + "/" + camera)

    images = []
    for f in os.listdir():
        if f.endswith('.png'):
            images.append(f)

    images.sort(key=lambda x: os.path.getmtime(x))


    # Determine the width and height from the first image
    frame = cv2.imread(images[0])
    height, width, channels = frame.shape

    # Define the codec and create a VideoWriter object
    output = camera + "_video.mp4"
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output, fourcc, fps, (width, height))

    # Make the video
    for image in images:
        frame = cv2.imread(image)
        out.write(frame)

    out.release()
    cv2.destroyAllWindows()

    print("The output video is {}".format(output))

# --------------------------------------------------
def main() -> None:
    """ Main controls the tool """

    # Get arguments from command line
    args = get_args()
    directory = args.directory
    duration = args.duration
    interval = args.interval
    v = args.verbosity

    # Find the number of Cameras attached
    cameras = usb.core.find(find_all=True,idVendor=0x32e4)
    num_Cams = len(list(cameras))

    # Create main directory and sub directories for each camera
    if not os.path.isdir(directory):
        os.mkdir(directory)
    for i in range(num_Cams):
        if not os.path.isdir(directory + "/camera_" + str(i+1)):
            os.mkdir(directory + "/camera_" + str(i+1))


    # Create Threads for each camera to loop on
    print("Starting to take pictures...")
    threads = []


    #   First Camera
    img_dir_1 = directory + "/camera_1"
    cam_1 = Thread(target=captureLoop,args=(img_dir_1, duration, interval, v, 0))
    cam_1.start()
    threads.append(cam_1)


    #   Second Camera
    if num_Cams > 1:
        img_dir_2 = directory + "/camera_2"
        cam_2 = Thread(target=captureLoop, args=(img_dir_1, duration, interval, v, 1))
        cam_2.start()
        threads.append(cam_2)

    # Join threads
    for i in threads:
        i.join()
    print("All Pictures Taken")

    # Time Lapse Mode
    if args.video:
        print("Condensing images into video...")
        for camera in os.listdir(directory):
            img2video(directory, camera, args.videoFrames)


    exit()

# --------------------------------------------------
if __name__ == '__main__':
    main()
